import textwrap
from datetime import date, datetime
from decimal import Decimal

import pytest

from pyathena.error import ProgrammingError

# A value whose single quote must not be allowed to terminate the string
# literal. Trino and Athena do not treat a backslash as an escape character
# inside a string literal, so a statement parsed by Trino must double the quote
# ('') rather than backslash-escape it (\').
HOSTILE = "a' OR 1=1 --"

# Statements parsed by the Trino/Athena engine, where single quotes must be
# doubled. DELETE and CTAS (CREATE TABLE ... AS SELECT) are the paths that
# CVE-2026-65321 left routed through the Hive escaper.
TRINO_STATEMENTS = [
    "SELECT * FROM t WHERE c = %(v)s",
    "WITH x AS (SELECT 1) SELECT * FROM t WHERE c = %(v)s",
    "INSERT INTO t VALUES (%(v)s)",
    "UPDATE t SET c = %(v)s",
    "MERGE INTO t USING s ON t.c = %(v)s",
    "DELETE FROM t WHERE c = %(v)s",
    "delete from t where c = %(v)s",
    "CREATE TABLE t WITH (format = 'PARQUET') AS SELECT * FROM s WHERE c = %(v)s",
    "CREATE VIEW v AS SELECT * FROM s WHERE c = %(v)s",
    "EXPLAIN DELETE FROM t WHERE c = %(v)s",
    "UNLOAD (SELECT * FROM t WHERE c = %(v)s) TO 's3://b/p/' WITH (format = 'PARQUET')",
    "/* generated by etl */ DELETE FROM t WHERE c = %(v)s",
    "-- nightly compaction\nDELETE FROM t WHERE c = %(v)s",
    "/* a */\n-- b\nDELETE FROM t WHERE c = %(v)s",
    "/* multi\nline */\nDELETE FROM t WHERE c = %(v)s",
    "\n\t DELETE FROM t WHERE c = %(v)s",
    # Near-miss statements: their prefixes are adjacent to the Hive allowlist
    # (ALTER/DROP/CREATE ... VIEW, VALUES) but Trino executes them, so they must
    # NOT be misrouted to the Hive escaper.
    "ALTER VIEW v AS SELECT name FROM s WHERE c = %(v)s",
    "DROP VIEW v -- %(v)s",
    "CREATE OR REPLACE VIEW v AS SELECT %(v)s",
    "VALUES (%(v)s)",
]

# Statements parsed by the Hive DDL engine, where backslash escaping is correct.
HIVE_STATEMENTS = [
    "CREATE EXTERNAL TABLE t (c string) LOCATION %(v)s",
    "CREATE TABLE t (c string) LOCATION %(v)s",
    "CREATE DATABASE d LOCATION %(v)s",
    "ALTER TABLE t SET LOCATION %(v)s",
    "DROP TABLE t PURGE -- %(v)s",
    "MSCK REPAIR TABLE t -- %(v)s",
    "SHOW PARTITIONS t -- %(v)s",
    "DESCRIBE t -- %(v)s",
    "CREATE SCHEMA s LOCATION %(v)s",
    "DROP DATABASE d -- %(v)s",
    "ALTER DATABASE d SET DBPROPERTIES ('k' = %(v)s)",
    # Leading comments must be stripped before detection on the Hive side too,
    # otherwise a commented Hive DDL statement would silently lose its escaping.
    "-- cleanup\nDROP TABLE t LOCATION %(v)s",
    "/* migrate */ ALTER TABLE t SET LOCATION %(v)s",
    "-- a\n-- b\nCREATE EXTERNAL TABLE t (c string) LOCATION %(v)s",
]


class TestDefaultParameterFormatter:
    def test_add_partition(self, formatter):
        expected = textwrap.dedent(
            """
            ALTER TABLE test_table
            ADD PARTITION (dt=DATE '2017-01-01', hour=1)
            """
        ).strip()

        actual = formatter.format(
            textwrap.dedent(
                """
                ALTER TABLE test_table
                ADD PARTITION (dt=%(dt)s, hour=%(hour)d)
                """
            ).strip(),
            {"dt": date(2017, 1, 1), "hour": 1},
        )
        assert actual == expected

    def test_drop_partition(self, formatter):
        expected = textwrap.dedent(
            """
            ALTER TABLE test_table
            DROP PARTITION (dt=DATE '2017-01-01', hour=1)
            """
        ).strip()

        actual = formatter.format(
            textwrap.dedent(
                """
                ALTER TABLE test_table
                DROP PARTITION (dt=%(dt)s, hour=%(hour)d)
                """
            ).strip(),
            {"dt": date(2017, 1, 1), "hour": 1},
        )
        assert actual == expected

    def test_format_none(self, formatter):
        expected = textwrap.dedent(
            """
            SELECT *
            FROM test_table
            WHERE col is null
            """
        ).strip()

        actual = formatter.format(
            textwrap.dedent(
                """
                SELECT *
                FROM test_table
                WHERE col is %(param)s
                """
            ).strip(),
            {"param": None},
        )
        assert actual == expected

    def test_format_datetime(self, formatter):
        expected = textwrap.dedent(
            """
            SELECT *
            FROM test_table
            WHERE col_timestamp >= TIMESTAMP '2017-01-01 12:00:00.000'
            AND col_timestamp <= TIMESTAMP '2017-01-02 06:00:00.000'
            """
        ).strip()

        actual = formatter.format(
            textwrap.dedent(
                """
                SELECT *
                FROM test_table
                WHERE col_timestamp >= %(start)s
                AND col_timestamp <= %(end)s
                """
            ).strip(),
            {
                "start": datetime(2017, 1, 1, 12, 0, 0),
                "end": datetime(2017, 1, 2, 6, 0, 0),
            },
        )
        assert actual == expected

    def test_format_date(self, formatter):
        expected = textwrap.dedent(
            """
            SELECT *
            FROM test_table
            WHERE col_date between DATE '2017-01-01' and DATE '2017-01-02'
            """
        ).strip()

        actual = formatter.format(
            textwrap.dedent(
                """
                SELECT *
                FROM test_table
                WHERE col_date between %(start)s and %(end)s
                """
            ).strip(),
            {"start": date(2017, 1, 1), "end": date(2017, 1, 2)},
        )
        assert actual == expected

    def test_format_int(self, formatter):
        expected = textwrap.dedent(
            """
            SELECT *
            FROM test_table
            WHERE col_int = 1
            """
        ).strip()

        actual = formatter.format(
            textwrap.dedent(
                """
                SELECT *
                FROM test_table
                WHERE col_int = %(param)s
                """
            ).strip(),
            {"param": 1},
        )
        assert actual == expected

    def test_format_float(self, formatter):
        expected = textwrap.dedent(
            """
            SELECT *
            FROM test_table
            WHERE col_float >= 0.1
            """
        ).strip()

        actual = formatter.format(
            textwrap.dedent(
                """
                SELECT *
                FROM test_table
                WHERE col_float >= %(param).1f
                """
            ).strip(),
            {"param": 0.1},
        )
        assert actual == expected

    def test_format_decimal(self, formatter):
        expected = textwrap.dedent(
            """
            SELECT *
            FROM test_table
            WHERE col_decimal <= DECIMAL '0.0000000001'
            """
        ).strip()

        actual = formatter.format(
            textwrap.dedent(
                """
                SELECT *
                FROM test_table
                WHERE col_decimal <= %(param)s
                """
            ).strip(),
            {"param": Decimal("0.0000000001")},
        )
        assert actual == expected

    def test_format_bool(self, formatter):
        expected = textwrap.dedent(
            """
            SELECT *
            FROM test_table
            WHERE col_boolean = True
            """
        ).strip()

        actual = formatter.format(
            textwrap.dedent(
                """
                SELECT *
                FROM test_table
                WHERE col_boolean = %(param)s
                """
            ).strip(),
            {"param": True},
        )
        assert actual == expected

    def test_format_str(self, formatter):
        expected = textwrap.dedent(
            """
            SELECT *
            FROM test_table
            WHERE col_string = 'amazon athena'
            """
        ).strip()

        actual = formatter.format(
            textwrap.dedent(
                """
                SELECT *
                FROM test_table
                WHERE col_string = %(param)s
                """
            ).strip(),
            {"param": "amazon athena"},
        )
        assert actual == expected

    def test_format_unicode(self, formatter):
        expected = textwrap.dedent(
            """
            SELECT *
            FROM test_table
            WHERE col_string = '密林 女神'
            """
        ).strip()

        actual = formatter.format(
            textwrap.dedent(
                """
                SELECT *
                FROM test_table
                WHERE col_string = %(param)s
                """
            ).strip(),
            {"param": "密林 女神"},
        )
        assert actual == expected

    def test_format_none_list(self, formatter):
        expected = textwrap.dedent(
            """
            SELECT *
            FROM test_table
            WHERE col IN (null, null)
            """
        ).strip()

        actual = formatter.format(
            textwrap.dedent(
                """
                SELECT *
                FROM test_table
                WHERE col IN %(param)s
                """
            ).strip(),
            {"param": [None, None]},
        )
        assert actual == expected

    def test_format_datetime_list(self, formatter):
        expected = textwrap.dedent(
            """
            SELECT *
            FROM test_table
            WHERE col_timestamp IN
            (TIMESTAMP '2017-01-01 12:00:00.000', TIMESTAMP '2017-01-02 06:00:00.000')
            """
        ).strip()

        actual = formatter.format(
            textwrap.dedent(
                """
                SELECT *
                FROM test_table
                WHERE col_timestamp IN
                %(param)s
                """
            ).strip(),
            {"param": [datetime(2017, 1, 1, 12, 0, 0), datetime(2017, 1, 2, 6, 0, 0)]},
        )
        assert actual == expected

    def test_format_date_list(self, formatter):
        expected = textwrap.dedent(
            """
            SELECT *
            FROM test_table
            WHERE col_date IN (DATE '2017-01-01', DATE '2017-01-02')
            """
        ).strip()

        actual = formatter.format(
            textwrap.dedent(
                """
                SELECT *
                FROM test_table
                WHERE col_date IN %(param)s
                """
            ).strip(),
            {"param": [date(2017, 1, 1), date(2017, 1, 2)]},
        )
        assert actual == expected

    def test_format_int_list(self, formatter):
        expected = textwrap.dedent(
            """
            SELECT *
            FROM test_table
            WHERE col_int IN (1, 2)
            """
        ).strip()

        actual = formatter.format(
            textwrap.dedent(
                """
                SELECT *
                FROM test_table
                WHERE col_int IN %(param)s
                """
            ).strip(),
            {"param": [1, 2]},
        )
        assert actual == expected

    def test_format_float_list(self, formatter):
        # default precision is 6
        expected = textwrap.dedent(
            """
            SELECT *
            FROM test_table
            WHERE col_float IN (0.100000, 0.200000)
            """
        ).strip()

        actual = formatter.format(
            textwrap.dedent(
                """
                SELECT *
                FROM test_table
                WHERE col_float IN %(param)s
                """
            ).strip(),
            {"param": [0.1, 0.2]},
        )
        assert actual == expected

    def test_format_decimal_list(self, formatter):
        expected = textwrap.dedent(
            """
            SELECT *
            FROM test_table
            WHERE col_decimal IN (DECIMAL '0.0000000001', DECIMAL '99.9999999999')
            """
        ).strip()

        actual = formatter.format(
            textwrap.dedent(
                """
                SELECT *
                FROM test_table
                WHERE col_decimal IN %(param)s
                """
            ).strip(),
            {"param": [Decimal("0.0000000001"), Decimal("99.9999999999")]},
        )
        assert actual == expected

    def test_format_bool_list(self, formatter):
        expected = textwrap.dedent(
            """
            SELECT *
            FROM test_table
            WHERE col_boolean IN (True, False)
            """
        ).strip()

        actual = formatter.format(
            textwrap.dedent(
                """
                SELECT *
                FROM test_table
                WHERE col_boolean IN %(param)s
                """
            ).strip(),
            {"param": [True, False]},
        )
        assert actual == expected

    def test_format_str_list(self, formatter):
        expected = textwrap.dedent(
            """
            SELECT *
            FROM test_table
            WHERE col_string IN ('amazon', 'athena')
            """
        ).strip()

        actual = formatter.format(
            textwrap.dedent(
                """
                SELECT *
                FROM test_table
                WHERE col_string IN %(param)s
                """
            ).strip(),
            {"param": ["amazon", "athena"]},
        )
        assert actual == expected

    def test_format_unicode_list(self, formatter):
        expected = textwrap.dedent(
            """
            SELECT *
            FROM test_table
            WHERE col_string IN ('密林', '女神')
            """
        ).strip()

        actual = formatter.format(
            textwrap.dedent(
                """
                SELECT *
                FROM test_table
                WHERE col_string IN %(param)s
                """
            ).strip(),
            {"param": ["密林", "女神"]},
        )
        assert actual == expected

    def test_format_bad_parameter(self, formatter):
        pytest.raises(
            ProgrammingError,
            lambda: formatter.format(
                """
                SELECT *
                FROM test_table
                where col_int = $(param)d
                """.strip(),
                1,
            ),
        )

        pytest.raises(
            ProgrammingError,
            lambda: formatter.format(
                """
                SELECT *
                FROM test_table
                where col_string = $(param)s
                """.strip(),
                "a string",
            ),
        )

        pytest.raises(
            ProgrammingError,
            lambda: formatter.format(
                """
                SELECT *
                FROM test_table
                where col_string in $(param)s
                """.strip(),
                ["a string"],
            ),
        )

    @pytest.mark.parametrize("operation", TRINO_STATEMENTS)
    def test_trino_statements_use_quote_doubling(self, formatter, operation):
        result = formatter.format(operation, {"v": HOSTILE})
        assert "\\'" not in result, f"backslash escaping leaked into: {result}"
        assert "''" in result

    @pytest.mark.parametrize("operation", HIVE_STATEMENTS)
    def test_hive_ddl_keeps_backslash_escaping(self, formatter, operation):
        assert "\\'" in formatter.format(operation, {"v": HOSTILE})

    def test_quote_cannot_terminate_literal_in_delete(self, formatter):
        result = formatter.format("DELETE FROM t WHERE c = %(v)s", {"v": HOSTILE})
        # Every quote in the rendered value is doubled, so the literal opened by
        # the formatter is still open until its own closing quote.
        assert result.count("'") % 2 == 0
        assert result == "DELETE FROM t WHERE c = 'a'' OR 1=1 --'"

    def test_ctas_detection_is_case_and_whitespace_insensitive(self, formatter):
        for operation in (
            "create  table  t  as  select %(v)s",
            "CREATE\nTABLE\nt\nAS\nSELECT %(v)s",
        ):
            assert "\\'" not in formatter.format(operation, {"v": HOSTILE})

    def test_table_name_starting_with_as_is_still_hive_ddl(self, formatter):
        # `as_of` must not be mistaken for the CTAS `AS` keyword.
        assert "\\'" in formatter.format(
            "CREATE EXTERNAL TABLE as_of (c string) LOCATION %(v)s", {"v": HOSTILE}
        )
