# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html
from datetime import datetime, timezone
from pathlib import Path


def get_version():
    try:
        # Try to import from _version.py (generated by setuptools-scm)
        from pyathena._version import __version__
        return __version__
    except ImportError:
        try:
            # Fallback to importlib.metadata
            from importlib.metadata import version
            return version("PyAthena")
        except Exception:
            return "unknown"


# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = "PyAthena"
copyright = f"{datetime.now(timezone.utc).year}, laughingman7743"
author = "laughingman7743"
version = f"v{get_version()}"
release = f"v{get_version()}"

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.viewcode",
    "sphinx.ext.napoleon",
    "sphinx.ext.intersphinx",
    "sphinx.ext.githubpages",
    "sphinx_multiversion",
]

# Napoleon settings for Google-style docstrings
napoleon_google_docstring = True
napoleon_numpy_docstring = False
napoleon_include_init_with_doc = False
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_preprocess_types = False
napoleon_type_aliases = None
napoleon_attr_annotations = True

# Autodoc settings
autodoc_default_options = {
    'members': True,
    'member-order': 'bysource',
    'special-members': '__init__',
    'undoc-members': True,
    'exclude-members': '__weakref__'
}

# Autosummary settings
autosummary_generate = True
autosummary_imported_members = False

# Intersphinx mapping
intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'pandas': ('https://pandas.pydata.org/pandas-docs/stable', None),
    'pyarrow': ('https://arrow.apache.org/docs/', None),
}

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]


# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = "furo"
html_static_path = ["_static"]
html_css_files = [
    "custom.css",
]

# Furo theme options
html_theme_options = {
    "source_repository": "https://github.com/laughingman7743/PyAthena/",
    "source_branch": "master",
    "source_directory": "docs/",
}

# Sidebar templates
html_sidebars = {
    "**": [
        "sidebar/brand.html",
        "sidebar/search.html",
        "sidebar/scroll-start.html",
        "sidebar/navigation.html",
        "versioning.html",
        "sidebar/scroll-end.html",
    ]
}

# -- Sphinx-multiversion configuration ----------------------------------------

# Whitelist pattern for tags
smv_tag_whitelist = r"^v3\.\d+\.\d+$"  # Match v3.x.x tags only

# Whitelist pattern for branches
smv_branch_whitelist = r"^master$"  # Only build master branch

# Whitelist pattern for remotes
smv_remote_whitelist = r"^origin$"  # Only build from origin remote

# Output all versions to the root directory
smv_outputdir_format = "{ref.name}"

# Specify the latest version (used for stable redirect)
smv_latest_version = "master"
